# Generated by Django 4.2.4 on 2024-07-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_user_reset_password_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_password_token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
