# Generated by Django 4.2.4 on 2024-06-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crud_user", "0002_userprofile_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
