# Generated by Django 4.2.4 on 2024-06-11 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crud_user", "0003_delete_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
